In [1]:
import torch

In [2]:
# A tensor is an n-dimensional array: a number,vector, matrix
#Number
t1 = torch.tensor(4.)

In [3]:
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
# Vector
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [9]:
# matrix
t3 = torch.tensor([[1.,3], [4,7], [8,11]])
t3

tensor([[ 1.,  3.],
        [ 4.,  7.],
        [ 8., 11.]])

In [12]:
# 3-dimensional array
t4 = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
t4

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

# All arguments to a tensor would be mapped to the same type

In [14]:
t4.shape

torch.Size([4, 3])

In [15]:
t1.shape

torch.Size([])

In [16]:
t2.shape

torch.Size([4])

In [17]:
t3.shape

torch.Size([3, 2])

# Tensor Opertations and gradients

In [18]:
# create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True) 
b = torch.tensor(5., requires_grad=True) 

In [19]:
# Arithmetic Operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [20]:
# Compute dderivatives
y.backward()

In [21]:
# Display
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


# Interoperability with numpy

In [22]:
import numpy as np
x = np.array([[1,2], [3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [23]:
y = torch.from_numpy(x)   # changes inplace
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [24]:
y = torch.tensor(x)   # creates a copy
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [25]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [26]:
# convert a tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

differnce between pytorch and numpy?
pytorch has been designed to work on GPUs which can do matrix opeerations fast in parallel